### ISSUE TITLE
Why clone instead of fork?

### ISSUE THREAD

**Issue by orweinberger** [israelcoin/Isracoin#4]
You guys chose to clone either the dogecoin repo or the litecoin repo and you've uploaded it into a new repository.

This has a huge downside since it means that any future development on the original repository will be very difficult for you to consume and will require a lot of manual work.

If you have chosen to fork the repository, you could use github's downstream and upstream mechanism that allows you to create pull-requests and consume future code updates.

Downstream/upstreams allows you to react quickly to critical code updates and is vital (in my opinion).

**Comment by guysoft** [comment]
@orweinberger We decided to clone because when you look at the netwrok map its much easier to differentiate between Isracoin developers and dogecoin / litecoin.

Dogecoin was picked was a decision of @israelcoin dev.

We can still pull and push locally without github's web interface.

**Comment by guysoft** [comment]
OK, did an attempt to merge Dogecoin develop branch with Isracoin's isracoin-1.6 branch, and its quite obvious that we can't just fetch stuff from there, because the are things we have to maintain on our side. So indeed there is no real benefit from using github's forking interface. There is, however, a benefit in cherry picking commits, which we can do because we did clone from Dogecoin.
